name: ci

permissions: read-all

on:
  pull_request:

jobs:
  super-linter:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter/slim@v7
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JSCPD: false

  docker-build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker metadata action
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: patroni-selfheal-local
          tags: |
            type=raw,latest

      - name: Build Dockerimage
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=docker,dest=/tmp/patroni-selfheal-local.tar
          platforms: linux/amd64
          push: false
          tags: ${{ steps.meta.outputs.tags }}

  dependabot-automerge:
    name: Auto Merge (Dependabot)
    needs:
      - docker-build
      - super-linter
    uses: Staffbase/gha-workflows/.github/workflows/template_automerge_dependabot.yml@v7.8.0
    with:
      force: true
    secrets:
      app_id: ${{ vars.STAFFBASE_ACTIONS_APP_ID }}
      private_key: ${{ secrets.STAFFBASE_ACTIONS_PRIVATE_KEY }}
